-- Default colors
	INVALID_COLOR     = { r = 1.0, g = 0.0, b = 0.0, };  -- Red
	NORMAL_COLOR    = { r = 0.0, g = 1.0, b = 0.0, };  -- Green
	PART_NORMAL   = { r = 0.8, g = 0.6, b = 0.0, };  -- Orange
	CAN_NOT_BE_TEST   = { r = 0.0, g = 0.0, b = 1.0, };  -- BLue
	
wnet_talents =
{  -- классы
	{ -- класс "DEATHKNIGHT",
	},
	{ --класс "Druid"
		{
			["Improved Nature's Grasp"] = INVALID_COLOR,
			["Dreamstate"] = INVALID_COLOR,
			["Improved Faerie Fire"] = INVALID_COLOR,
			["Nature's Grasp"] = PART_NORMAL,
			["Brambles"] = PART_NORMAL,
			["Insect Swarm"] = PART_NORMAL,
			["Nature's Reach"] = PART_NORMAL,
			["Lunar Guidance"] = PART_NORMAL,
			["Nature's Grace"] = PART_NORMAL,
			["Moonkin Form"] = PART_NORMAL,
			["Wrath of Cenarius"] = PART_NORMAL,
			["Force of Nature"] = PART_NORMAL,
		},
		{
			["Feral Instinct"] = INVALID_COLOR,
			["Shredding Attacks"] = INVALID_COLOR,
			["Nurturing Instinct"] = INVALID_COLOR,
			["Primal Tenacity"] = INVALID_COLOR,
			["Leader of the Pack"] = INVALID_COLOR,
			["Improved Leader of the Pack"] = INVALID_COLOR,
			["Predatory Instincts"] = INVALID_COLOR,
			["Ferocity"] = PART_NORMAL,
			["Feral Aggression"] = PART_NORMAL,
			["Thick Hide"] = PART_NORMAL,
			["Feral Swiftness"] = PART_NORMAL,
			["Feral Charge"] = PART_NORMAL,
			["Primal Fury"] = PART_NORMAL,
			["Savage Fury"] = PART_NORMAL,
			["Heart of the Wild"] = PART_NORMAL,
			["Survival of the Fittest"] = PART_NORMAL,
			["Mangle"] = PART_NORMAL,
		},
		{
			["Intensity"] = INVALID_COLOR,
			["Subtlety"] = INVALID_COLOR,
			["Improved Rejuvenation"] = INVALID_COLOR,
			["Improved Tranquility"] = INVALID_COLOR,
			["Gift of Nature"] = INVALID_COLOR,
			["Empowered Touch"] = INVALID_COLOR,
			["Swiftmend"] = INVALID_COLOR,
			["Natural Shapeshifter"] = PART_NORMAL,
			["Empowered Rejuvenation"] = PART_NORMAL,
			["Tree of Life"] = PART_NORMAL,
		},
	},
	{ --класс "Hunter"
		{
			["Improved Aspect of the Hawk"] = INVALID_COLOR,
			["Focused Fire"] = INVALID_COLOR,
			["Improved Revive Pet"] = INVALID_COLOR,
			["Pathfinding"] = INVALID_COLOR,
			["Bestial Swiftness"] = INVALID_COLOR,
			["Unleashed Fury"] = INVALID_COLOR,
			["Improved Mend Pet"] = INVALID_COLOR,
			["Ferocity"] = INVALID_COLOR,
			["Spirit Bond"] = INVALID_COLOR,
			["Imtimidation"] = INVALID_COLOR,
			["Bestial Discipline"] = INVALID_COLOR,
			["Animal Handler"] = INVALID_COLOR,
			["Frenzy"] = INVALID_COLOR,
			["Ferocious Inspiration"] = INVALID_COLOR,
			["Bestial Wrath"] = INVALID_COLOR,
			["Serpent's Swiftness"] = INVALID_COLOR,
			["The Beast Within"] = INVALID_COLOR,
			["Catlike Reflexes"] = PART_NORMAL,
		},
		{
			["Improved Hunter's Mark"] = INVALID_COLOR,
			["Go for the Throat"] = INVALID_COLOR,
			["Improved Stings"] = INVALID_COLOR,
			["Rapid Killing"] = INVALID_COLOR,
			["Improved Barrage"] = PART_NORMAL,
		},
		{
			["Entrapment"] = INVALID_COLOR,
			["Clever Taps"] = INVALID_COLOR,
			["Improved Feign Death"] = INVALID_COLOR,
			["Trap Mastery"] = PART_NORMAL,
			["Surefooted"] = PART_NORMAL,
			["Killer Instinct"] = PART_NORMAL,
			["Counterattack"] = PART_NORMAL,
			["Wyvern Sting"] = PART_NORMAL,
			["Expose Weakness"] = PART_NORMAL,
		},
	},
	{ --класс "Mage"
		{
			["Arcane Subtlety"] = INVALID_COLOR,
			["Arcane Focus"] = INVALID_COLOR,
			["Improved Mana Shield"] = INVALID_COLOR,
			["Empowered Arcane Missiles"] = INVALID_COLOR,
			["Magic Absorption"] = PART_NORMAL,
		},
		{
			["Improved Fire Ward"] = INVALID_COLOR,
			["Ignite"] = PART_NORMAL,
			["Master of Elements"] = PART_NORMAL,
			["Combustion"] = PART_NORMAL,
		},
		{
			["Improved Blizzard"] = INVALID_COLOR,
			["Shatter"] = INVALID_COLOR,
			["Frost Warding"] = PART_NORMAL,
			["Elemental Precision"] = PART_NORMAL,
			["Summon Water Elemental"] = PART_NORMAL,
		},
	},
	{ --класс "Paladin"
		{
			["Spiritual Focus"] = PART_NORMAL,
			["Unyielding Faith"] = INVALID_COLOR,
			["Pure of Heart"] = INVALID_COLOR,
			["Light's Grace"] = INVALID_COLOR,
			["Healing Light"] = PART_NORMAL,
			["Improved Lay on Hands"] = PART_NORMAL,
			["Divine Favor"] = PART_NORMAL,
			["Purifying Power"] = PART_NORMAL,
			["Holy Shock"] = PART_NORMAL,
			["Aura Mastery"] = CAN_NOT_BE_TEST,
		},
		{
			["Improved Concentration Aura"] = INVALID_COLOR,
			["Combat Expertise"] = PART_NORMAL,
			["Redoubt"] = PART_NORMAL,
			["Blessing of Sanctuary"] = PART_NORMAL,
			["Precision"] = INVALID_COLOR,
			["Stoicism"] = INVALID_COLOR,
			["Reckoning"] = PART_NORMAL,
		},
		{
			["Benediction"] = INVALID_COLOR,
			["Pursuit of Justice"] = INVALID_COLOR,
			["Crusade"] = INVALID_COLOR,
			["Improved Sanctity Aura"] = INVALID_COLOR,
			["Fanaticism"] = INVALID_COLOR,
			["Improved Seal of the Crusader"] = PART_NORMAL,
			["Vindication"] = PART_NORMAL,
			["Seal of Command"] = PART_NORMAL,
			["Venegeance"] = PART_NORMAL,
			["Crusader Strike"] = PART_NORMAL,
		},
	},
	{ --класс ["PRIEST"]
		{ -- дисциплина
			["Unbreakable Will"] = PART_NORMAL,
			["Silent Resolve"] = PART_NORMAL,
			["Martyrdom"] = PART_NORMAL,
			["Meditation"] = INVALID_COLOR,
			["Force of Will"] = PART_NORMAL,
			["Improved Divine Spirit"] = PART_NORMAL,
			["Focused Will"] = PART_NORMAL,
			["Reflective Shield"] = INVALID_COLOR,
			["Pain Suppression"] =PART_NORMAL,
		},
		{ -- holy
			["Holy Nova"] = PART_NORMAL,
			["Blessed Recovery"] = PART_NORMAL,
			["Spirit of Redemption"] = PART_NORMAL,
			["Spirit of Redemption"] = PART_NORMAL,
			["Blessed Resilience"] = INVALID_COLOR,
			["Empowered Healing"] = INVALID_COLOR,
			["Circle of Healing"] = PART_NORMAL,
		},
		{ -- Shadow
			["Spirit Tap"] = PART_NORMAL,
			["Shadow Affinity"] = INVALID_COLOR,
			["Shadow Focus"] = INVALID_COLOR,
			["Mind Melt"] = INVALID_COLOR,
			["Darkness"] = NORMAL_COLOR,
			["Shadowform"] = PART_NORMAL,
			["Shadow Resilience"] = INVALID_COLOR,
		},
	},
	{ --класс "Rogue"
		{
			["Murder"] = INVALID_COLOR,
			["Improved Poisons"] = INVALID_COLOR,
			["Quick Recovery"] = PART_NORMAL,
			["Seal Fate"] = PART_NORMAL,
			["Master Poisoner"] = INVALID_COLOR,
			["Deadened Nerves"] = INVALID_COLOR,
			["Ruthlessness"] = PART_NORMAL,
			["Vile Poisons"] = PART_NORMAL,
			["Fleet Footed"] = PART_NORMAL,
			["Cold Blood"] = PART_NORMAL,
		},
		{
			["Weapon Expertise"] = INVALID_COLOR,
			["Adrenaline Rush"] = INVALID_COLOR,
			["Nerves of Steel"] = INVALID_COLOR,
			["Combat Potency"] = INVALID_COLOR,
			["Improved Slice and Dice"] = PART_NORMAL,
			["Riposte"] = PART_NORMAL,
			["Dagger Specialization"] = PART_NORMAL,
			["Dual Wield Specialization"] = PART_NORMAL,
			["Mace Specialization"] = PART_NORMAL,
			["Sword Specialization"] = PART_NORMAL,
			["First Weapon Specialization"] = PART_NORMAL,
			["Blade Twisting"] = PART_NORMAL,
			["Precision"] = CAN_NOT_BE_TEST,
		},
		{
			["Sleight of Hand"] = INVALID_COLOR,
			["Serrated Blades"] = INVALID_COLOR,
			["Master of Subtlety"] = INVALID_COLOR,
			["Setup"] = PART_NORMAL,
			["Heightened Senses"] = PART_NORMAL,
			["Shadowstep"] = PART_NORMAL,
			["Master of Deception"] = CAN_NOT_BE_TEST,
			["Enveloping Shadows"] = CAN_NOT_BE_TEST,
		},
	},
	{ --класс "Shaman"
		{
			["Earth's Grasp"] = INVALID_COLOR,
			["Call of Flame"] = INVALID_COLOR,
			["Improved Fire Nova Totem"] = INVALID_COLOR,
			["Elemental Shields"] = INVALID_COLOR,
			["Lightning Overload"] = INVALID_COLOR,
			["Elemental Focus"] = PART_NORMAL,
			["Elemental Precision"] = PART_NORMAL,
			["Elemental Mastery"] = PART_NORMAL,
		},
		{
			["Guardian Totems"] = INVALID_COLOR,
			["Enchanting Totems"] = INVALID_COLOR,
			["Improved Weapon Totems"] = INVALID_COLOR,
			["Spirit Weapons"] = INVALID_COLOR,
			["Elemental Weapons"] = INVALID_COLOR,
			["Dual Wield Specialization"] = INVALID_COLOR,
			["Shield Specialization"] = PART_NORMAL,
			["Flurry"] = PART_NORMAL,
			["Mental Quickness"] = PART_NORMAL,
			["Stormstrike"] = PART_NORMAL,
			["Shamanistic Rage"] = PART_NORMAL,
		},
		{
			["Improved Reincarnation"] = INVALID_COLOR,
			["Totemic Mastery"] = INVALID_COLOR,
			["Restorative Totems"] = INVALID_COLOR,
			["Healing Way"] = INVALID_COLOR,
			["Focused Mind"] = INVALID_COLOR,
			["Mana Tide Totem"] = INVALID_COLOR,
			["Improved Chain Heal"] = INVALID_COLOR,
			["Ancestral Healing"] = PART_NORMAL,
			["Totemic Focus"] = PART_NORMAL,
			["Nature's Guidance"] = PART_NORMAL,
			["Nature's Blessing"] = PART_NORMAL,
			["Earth Shield"] = PART_NORMAL,
			["Healing Grace"] = CAN_NOT_BE_TEST,
		},
	},
	{ -- warlock
		{
			["Suppression"] = INVALID_COLOR,
			["Improved Drain Soul"] = INVALID_COLOR,
			["Soul Siphon"] = INVALID_COLOR,
			["Dark Pact"] = INVALID_COLOR,
			["Malediction"] = INVALID_COLOR,
			["Amplify Curse"] = PART_NORMAL,
			["Shadow Embrace"] = PART_NORMAL,
			["Siphon Life"] = PART_NORMAL,
			["Contagion"] = PART_NORMAL,
			["Unstable Affliction"] = PART_NORMAL,
		},
		{
			["Improved Health Funnel"] = INVALID_COLOR,
			["Improved Succubus"] = INVALID_COLOR,
			["Demonic Aegis"] = INVALID_COLOR,
			["Unholy Power"] = INVALID_COLOR,
			["Demonic Sacrifice"] = INVALID_COLOR,
			["Master Demonologist"] = INVALID_COLOR,
			["Demonic Resilience"] = INVALID_COLOR,
			["Soul Link"] = INVALID_COLOR,
			["Demonic Knowledge"] = INVALID_COLOR,
			["Improved Imp"] = PART_NORMAL,
			["Improved Voidwalker"] = PART_NORMAL,
			["Fel Intellect"] = PART_NORMAL,
			["Fel Stamina"] = PART_NORMAL,
			["Summon Felguard"] = PART_NORMAL,
			["Improved Enslave Demon"] = CAN_NOT_BE_TEST,
			["Mana Feed"] = CAN_NOT_BE_TEST,
		},
		{
			["Aftermath"] = PART_NORMAL,
			["Pyroclasm"] = PART_NORMAL,
			["Shadow and Flame"] = PART_NORMAL,
			["Improved Firebolt"] = CAN_NOT_BE_TEST,
		},
	},
	{ --warrior
		{
			["Improved Rend"] = INVALID_COLOR,
			["Iron Will"] = INVALID_COLOR,
			["Improved Overpower"] = INVALID_COLOR,
			["Improved Thunder Clap"] = PART_NORMAL,
			["Deep Wounds"] = PART_NORMAL,
			["Impale"] = PART_NORMAL,
			["Death Wish"] = PART_NORMAL,
			["Improved Disciplines"] = PART_NORMAL,
			["Mortal Strike"] = PART_NORMAL,
		},
		{
			["Sweeping Strikes"] = INVALID_COLOR,
			["Weapon Mastery"] = INVALID_COLOR,
			["Precision"] = INVALID_COLOR,
			["Rampage"] = INVALID_COLOR,
			["Booming Voice"] = PART_NORMAL,
		},
		{
			["Shield Mastery"] = INVALID_COLOR,
			["Last Stand"] = PART_NORMAL,
			["Improved Defensive Stance"] = PART_NORMAL,
			["Shield Slam"] = PART_NORMAL,
			["Focused Rage"] = PART_NORMAL,
			["Devastate"] = PART_NORMAL,
		},
	},
}

wnet_npc = {	
	["Archmage Xylem"] = 1,
	["Celebras the Cursed"] = 1,
	["Clandrath"] = 1,
	["Dama Wildmane"] = 1,
	["Dark Iron Taskmaster"] = 1,
	["Deadwood Avenger"] = 1,
	["Deadwood Den Watcher"] = 1,
	["Deadwood Gardener"] = 1,
	["Deadwood Pathfinder"] = 1,
	["Deadwood Shaman"] = 1,
	["Deadwood Warrior"] = 1,
	["Elder Rage Scar"] = 1,
	["Exarch Menelaous"] = 1,
	["Eyonix"] = 1,
	["Ferocious Rage Scar"] = 1,
	["Firemane Ash Tail"] = 1,
	["Firemane Scalebane"] = 1,
	["Firemane Scout"] = 1,
	["Gorrim"] = 1,
	["Green Wyrmkin"] = 1,
	["Hama"] = 1,
	["Harlo Wigglesworth"] = 1,
	["Hematus"] = 1,
	["High Protector Lorik"] = 1,
	["Illidari Taskmaster"] = 1,
	["Jadefire Hellcaller"] = 1,
	["Jadefire Rogue"] = 1,
	["Jadefire Shadowstalker"] = 1,
	["Jadefire Trickster"] = 1,
	["Khaelyn Steelwing"] = 1,
	["Kurll"] = 1,
	["Lebowski"] = 1,
	["Loorana"] = 1,
	["Lunix Sprocketslip"] = 1,
	["Meilosh"] = 1,
	["Minalei"] = 1,
	["Norman"] = 1,
	["Northspring Harpy"] = 1,
	["Northspring Roguefeather"] = 1,
	["Northspring Slayer"] = 1,
	["Northspring Windcaller"] = 1,
	["Overseer Azarad"] = 1,
	["Rage Scar Yeti"] = 1,
	["Rotting Cadaver"] = 1,
	["Rotting Worm"] = 1,
	["Shaleskin Flayer"] = 1,
	["Silithid Swarmer"] = 1,
	["Soolie Berryfizz"] = 1,
	["Stinglasher"] = 1,
	["Stonescythe Alpha"] = 1,
	["Stonescythe Whelp"] = 1,
	["Teribus the Cursed"] = 1,
	["Thulbek"] = 1,
	["Trull Failbane"] = 1,
	["Twilight Dark Shaman"] = 1,
	["Twilight Fire Guard"] = 1,
	["Twilight Geomancer"] = 1,
	["Twilight Idolater"] = 1,
	["Twilight Prophet"] = 1,
	["Wyrmcult Broodling"] = 1,
	["Wyrmkin Dreamwalker"] = 1,
	["Xavaric"] = 1,
	["Yuka Screwspigot"] = 1
};

--багнутые вещи (из темы "Ёпик шмот")
wnet_items = {
	["The Green Tower"] = 1,
	["Hammer of the Northern Wind"] = 1,
	["Blade of Eternal Darkness"] = 1,
	["Zandalarian Hero Charm"] = 1,
	["Eye of Gruul"] = 1,
	["Piccolo of the Flaming Fire"] = 1
};

--багнутые квесты (из соответствующего раздела форума)
wnet_quests = {
	["Flexing for Nougat"] = 1,
	["Claiming the Light"] = 1,
	["Rotting Hearts"] = 1,
	["More Rotting Hearts"] = 1,
	["Spinal Dust"] = 1,
	["More Spinal Dust"] = 1,
	["Kindness"] = 1,
	["Seek Out Neltharaku"] = 1,
	["Neltharaku's Tale"] = 1,
	["Infiltrating Dragonmaw Fortress"] = 1,
	["To Netherwing Ledge!"] = 1,
	["The Force of Neltharaku"] = 1,
	["Karynaku"] = 1,
	["Zuluhed the Whacked"] = 1,
	["Ally of the Netherwing"] = 1,
	["The missing diplomat"] = 1,
	["In Service of the Illidari"] = 1,
	["Fire Plume Forged"] = 1,
	["A Demonstration of Loyalty"] = 1,
	["Cho'war the Pillager"] = 1,
	["Turning Point"] = 1,
	["The Dark Missive"] = 1,
	["The Trappings of a Vindicator"] = 1,
	["The Gordok Ogre Suit"] = 1,
	["Goodnight, Gronn"] = 1,
	["The Heart of Darkness"] = 1,
	["Swift Discipline"] = 1,
	["The Ethereum"] = 1,
	["Surveying the Ruins"] = 1,
	["Winterhoof Cleansing"] = 1,
	["The Curse of the Tides"] = 1,
	["Looking Further"] = 1,
	["How to Serve Goblins"] = 1,
	["Prospector Balmoral"] = 1,
	["The Missing Merchant"] = 1,
	["Information Gathering"] = 1,
	["Saving the Best for Last"] = 1,
	["Freed from the Hive"] = 1,
	["Teleport This!"] = 1,
	["The Citadel's Reach"] = 1,
	["Fel Reavers, No Thanks!"] = 1,
	["Nether Gas In a Fel Fire Engine"] = 1,
	["Aurius' Reckoning"] = 1,
	["Testing the Antidote"] = 1,
	["Arikara"] = 1,
	["Ogre Thieves"] = 1,
	["Scratches"] = 1,
	["Doorway to the Abyss"] = 1,
	["It's a Secret to Everybody"] = 1,
	["To the Top"] = 1,
	["An Alternative Alternative"] = 1,
	["Maxnar Must Die!"] = 1,
	["Gorgrom the Dragon-Eater"] = 1,
	["Exorcising the Trees"] = 1,
	["Creating the Pendant"] = 1,
	["The Unending Invasion"] = 1,
	["Stymying the Arakkoa"] = 1,
	["Declawing Doomclaw"] = 1,
	["The Vengeful Harbinger"] = 1,
	["Crackin' Some Skulls"] = 1,
	["Welcoming the Wolf Spirit"] = 1,
	["The Principal Source"] = 1,
	["Whelps of the Wyrmcult"] = 1,
	["The Stones of Vekh'nir"] = 1,
	["Zalazane"] = 1,
	["Taming The Beast"] = 1,
	["Thwarting Kolkar Aggression"] = 1,
	["Shattering the Veil"] = 1,
	["And Now, the Moment of Truth"] = 1,
	["Report to Stonebreaker Camp"] = 1,
	["Clues in the Thicket"] = 1,
	["Report to the Allerian Post"] = 1,
	["Suppression"] = 1,
	["The Seer's Relic"] = 1,
	["An Ambitious Plan"] = 1,
	["Welcoming the Wolf Spirit"] = 1,
	["The Defias Brotherhood"] = 1,
	["Lost in Action"] = 1,
	["A Necessary Distraction"] = 1,
	["Quenching the Blade"] = 1,
	["Burn It Up... For the Horde!"] = 1,
	["Avruu's Orb"] = 1,
	["Wanted - Arnak Grimtotem"] = 1,
	["The Theramore Docks"] = 1,
	["Against the Legion"] = 1,
	["Secrets of the Talonpriests"] = 1,
	["Marking the Path"] = 1,
	["Arelion's Mistress"] = 1,
	["The Brood of Onyxia"] = 1,
	["Pursuing Terrorclaw"] = 1,
	["The Zapthrottle Mote Extractor!"] = 1,
	["Now That We're Friends..."] = 1,
	["Against All Odds"] = 1,
	["Kharan's Tale"] = 1,
	["A Taste of Flame"] = 1,
	["Enraged Wildkin"] = 1,
	["Tablet of the Seven"] = 1,
	["The Broken Sigil"] = 1,
	["Well of Corruption"] = 1,
	["Preparing the Salve"] = 1,
	["Mok'thardin's Enchantment"] = 1,
	["Distracting Jarven"] = 1,
	["Lost in Battle"] = 1,
	["A Little Dash of Seasoning"] = 1,
	["Badlands Reagent Run II"] = 1,
	["Gordunni Cobalt"] = 1,
	["To Legion Hold"] = 1,
	["Wanted Poster's"] = 1,
	["The Flesh Lies..."] = 1,
	["The Sacred Flame"] = 1,
	["The Warsong Reports"] = 1,
	["The Terror of Marshlight Lake"] = 1,
	["Overlord Gorefist"] = 1,
	["Mor'zul Bloodbringer"] = 1,
	["The Love Potion"] = 1,
	["Dwarven Digging"] = 1,
	["Torching Sunfury Hold"] = 1,
	["Body of Evidence"] = 1,
	["The Ashtongue Corruptors"] = 1,
	["You're Fired!"] = 1,
	["Restoring the Light"] = 1,
	["Concerted Efforts"] = 1,
	["Contact from Dalaran"] = 1,
	["What We Don't Know..."] = 1,
	["Getting the Bladespire Tanked"] = 1
};

--багнутые вещи, св€занные с професси€ми 
wnet_proff_item = {
--сначала записи о рецептах, схемах, планах и т.д.
--алхими€
	["Recipe: Major Dreamless Sleep Potion"] = 1,
	["Catseye Elixir"] = 1,
	["Recipe: Elixir of Empowerment"] = 1,
	["Recipe: Elixir of the Searching Eye"] = 1,
	["Recipe: Elixir of Dream Vision"] = 1,
	["Recipe: Sneaking Potion"] = 1,
	["Mad Alchemist's Potion"] = 1,
	["Recipe: Earthen Elixir"] = 1,
	["Recipe: Elixir of Ironskin"] = 1,
	["Recipe: Elixir of Major Agility"] = 1,

--инженери€
	["Schematic: Rocket Boots Xtreme"] = 1,
	["Gnomish Net-o-Matic Projector"] = 1,
	["Compact Harvest Reaper Kit"] = 1,
	["Schematic: Force Reactive Disk"] = 1,
	["Nigh Invulnerability Belt"] = 1,
	["Schematic: Goblin Land Mine"] = 1,
	["Schematic: Crashin' Thrashin' Robot"] = 1,
	["Explosive Sheep"] = 1,
	["Schematic: Goblin Rocket Helmet"] = 1,

--€ды
	["Wound Poison"] = 1,
	["Instant Poison"] = 1,
	["Deadly Poison"] = 1,

--тейлоринг
	["Pattern: Netherweave Net"] = 1,
	["Pattern: Frozen Shadoweave Boots"] = 1,
	["Pattern: Frozen Shadoweave Robe"] = 1,
	["Pattern: Frozen Shadoweave Shoulders"] = 1,
	["Pattern: Big Bag of Enchantment"] = 1,
	["Pattern: Cenarion Herb Bag"] = 1,

--ювелирка
	["Aquamarine Pendant of the Warrior"] = 1,
	["Figurine - Golden Hare"] = 1,

	["Drums of War"] = 1,
	["Drums of Restoration"] = 1,
	["Knothide Armor Kit"] = 1,

--кузнечное дело
	["Plans: Elemental Sharpening Stone"] = 1,
	["Plans: Steel Weapon Chain"] = 1,

--инчант
	["Formula: Enchant Weapon - Unholy"] = 1,
	["Formula: Enchant Weapon - Lifestealing"] = 1,

--а теперь - сами багнутые вещи								
	["Major Dreamless Sleep Potion"] = 1,
	["Elixir of Empowerment"] = 1,
	["Elixir of the Searching Eye"] = 1,
	["Elixir of Dream Vision"] = 1,
	["Sneaking Potion"] = 1,

	["Earthen Elixir"] = 1,
	["Elixir of Ironskin"] = 1,
	["Elixir of Major Agility"] = 1,

	["Rocket Boots Xtreme"] = 1,
	["Force Reactive Disk"] = 1,
	["Goblin Land Mine"] = 1,
	["Crashin' Thrashin' Robot"] = 1,
	["Goblin Rocket Helmet"] = 1,

	["Netherweave Net"] = 1,
	["Frozen Shadoweave Boots"] = 1,
	["Frozen Shadoweave Robe"] = 1,
	["Frozen Shadoweave Shoulders"] = 1,
	["Big Bag of Enchantment"] = 1,
	["Cenarion Herb Bag"] = 1,

	["Elemental Sharpening Stone"] = 1,
	["Steel Weapon Chain"] = 1,

	["Enchant Weapon - Unholy"] = 1,
	["Enchant Weapon - Lifestealing"] = 1
};
